---
- name: Setup Pi
  hosts: pi
  tasks:
    - name: Install docker
      become: yes
      ansible.builtin.import_tasks:
        file: tasks/docker.yml

    - name: Install Portainer
      become: yes
      ansible.builtin.import_tasks:
        file: tasks/portainer.yml